name: Create Release
on:
  workflow_dispatch:
    inputs:
      reason:
        description: "What's new about this release?"
        required: true
        default: 'Cooked something'
      version:
        description: "What's the version of this release?"
        required: true
        default: 'v0.0.0'

jobs: # i gave up so i just copied the build job
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get short SHA # idk why is this here so i decided to not touch it
        run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: "8.0"
      
      - name: Restore PhiInfo
        run: | 
          dotnet restore ./PhiInfo.Core/PhiInfo.Core.csproj
          dotnet restore ./PhiInfo.CLI/PhiInfo.CLI.csproj
      
      - name: Build PhiInfo
        run: | 
          dotnet build ./PhiInfo.Core/PhiInfo.Core.csproj -c Release
          dotnet build ./PhiInfo.CLI/PhiInfo.CLI.csproj -c Release
          dotnet build ./PhiInfo.CLI/PhiInfo.CLI.csproj -c AsLibrary
      
      - name: Pack PhiInfo
        run: | 
          dotnet pack ./PhiInfo.Core/PhiInfo.Core.csproj -c Release
          dotnet pack ./PhiInfo.CLI/PhiInfo.CLI.csproj -c Release
          dotnet pack ./PhiInfo.CLI/PhiInfo.CLI.csproj -c AsLibrary
      
      - name: Copy to Artifacts folder
        run: |
          mkdir -p /tmp/Artifacts
          cp ./PhiInfo.Core/bin/Release/*.nupkg /tmp/Artifacts/
          cp ./PhiInfo.CLI/bin/Release/*.nupkg /tmp/Artifacts/
          cp ./PhiInfo.CLI/bin/AsLibrary/*.nupkg /tmp/Artifacts/

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "${{ inputs.version }}" \
            /tmp/Artifacts/* \
            --title="Release ${{ inputs.version }}" \
            --generate-notes
