name: Create Release
on:
  workflow_dispatch:
    inputs:
      reason:
        description: "What's new about this release?"
        required: true
        default: 'Cooked something'
      version:
        description: "What's the version of this release?"
        required: true
        default: 'v0.0.0'

jobs:
  build_packages:
    uses: ./.github/workflows/dotnet.yml
  release:
    needs: build_packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          ls -al /tmp
          ls -al /tmp/Artifacts/
          gh release create "${{ inputs.version }}" \
            /tmp/Artifacts/* \
            --title="Release ${{ inputs.version }}" \
            --generate-notes
      - name: Cleanup
        run: rm -rf /tmp/Artifacts/
